// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwalzufqsrmkguwmzgad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3YWx6dWZxc3Jta2d1d216Z2FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzMzU2MDMsImV4cCI6MjA3NzkxMTYwM30.BZYZYAtU27Y0wY7bvwNW9n5k4yM0gvy_jSVQmGaOLzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});